// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qivbamplrsohrrytxzpi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFpdmJhbXBscnNvaHJyeXR4enBpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxODkwMDIsImV4cCI6MjA2ODc2NTAwMn0.uVq5k3UgI2-cIKMZUQY-CT02MhgLPYH_oSH88xClvZA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});